# Generated by Django 3.1.1 on 2021-05-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_LED_Strip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('power_status', models.BooleanField(default=False)),
                ('light_type', models.CharField(default='Light', max_length=255)),
            ],
        ),
    ]
