# Generated by Django 3.1.1 on 2021-05-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_device_led_strip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device_LED_Strip',
            new_name='DeviceLEDStrip',
        ),
    ]
